project_name: goidc-proxy
env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
    - go generate ./...
archives:
  - id: goidc-proxy
    builds:
      - goidc-proxy
    format: binary
builds:
  - id: goidc-proxy
    binary: goidc-proxy
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
    goarch:
      - amd64
universal_binaries:
  - id: goidc-proxy
    replace: false
dockers:
  - image_templates:
    - "tlyng/{{ .ProjectName }}:{{ .Version }}"
    - "tlyng/{{ .ProjectName }}:{{ .Major }}"
    - "tlyng/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "tlyng/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile.release
    skip_push: false
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/tlyng/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/tlyng/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: UNINETTSigma2

